// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"docs/demo/cropper-upload":{"path":"demo/cropper-upload","id":"docs/demo/cropper-upload","parentId":"DocLayout"},"docs/demo/upload-dragger":{"path":"demo/upload-dragger","id":"docs/demo/upload-dragger","parentId":"DocLayout"},"docs/demo/card-upload":{"path":"demo/card-upload","id":"docs/demo/card-upload","parentId":"DocLayout"},"docs/demo/extra-list":{"path":"demo/extra-list","id":"docs/demo/extra-list","parentId":"DocLayout"},"docs/demo/image-list":{"path":"demo/image-list","id":"docs/demo/image-list","parentId":"DocLayout"},"docs/demo/card-list":{"path":"demo/card-list","id":"docs/demo/card-list","parentId":"DocLayout"},"docs/demo/file-size":{"path":"demo/file-size","id":"docs/demo/file-size","parentId":"DocLayout"},"docs/demo/icon-list":{"path":"demo/icon-list","id":"docs/demo/icon-list","parentId":"DocLayout"},"docs/demo/max-count":{"path":"demo/max-count","id":"docs/demo/max-count","parentId":"DocLayout"},"docs/demo/text-list":{"path":"demo/text-list","id":"docs/demo/text-list","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}} as const;
  return {
    routes,
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "dumi__pages__404" */'@/dumi__pages/404')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__ContextWrapper" */'@/dumi__theme/ContextWrapper')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "dumi__theme__layouts__DocLayout" */'@/dumi__theme/layouts/DocLayout')),
'docs/demo/cropper-upload': React.lazy(() => import(/* webpackChunkName: "docs__demo__cropper-upload.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/cropper-upload.md')),
'docs/demo/upload-dragger': React.lazy(() => import(/* webpackChunkName: "docs__demo__upload-dragger.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/upload-dragger.md')),
'docs/demo/card-upload': React.lazy(() => import(/* webpackChunkName: "docs__demo__card-upload.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/card-upload.md')),
'docs/demo/extra-list': React.lazy(() => import(/* webpackChunkName: "docs__demo__extra-list.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/extra-list.md')),
'docs/demo/image-list': React.lazy(() => import(/* webpackChunkName: "docs__demo__image-list.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/image-list.md')),
'docs/demo/card-list': React.lazy(() => import(/* webpackChunkName: "docs__demo__card-list.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/card-list.md')),
'docs/demo/file-size': React.lazy(() => import(/* webpackChunkName: "docs__demo__file-size.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/file-size.md')),
'docs/demo/icon-list': React.lazy(() => import(/* webpackChunkName: "docs__demo__icon-list.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/icon-list.md')),
'docs/demo/max-count': React.lazy(() => import(/* webpackChunkName: "docs__demo__max-count.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/max-count.md')),
'docs/demo/text-list': React.lazy(() => import(/* webpackChunkName: "docs__demo__text-list.md" */'/Users/hubingjie/Desktop/react-upload-component/docs/demo/text-list.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "dumi__pages__Demo" */'@/dumi__pages/Demo')),
},
  };
}
